# ????
spring:
  #  config:
  #    activate:
  #      on-profile: ${profile.active}    # ???????? profile.active ?????????? Spring ?????????????????????????????profile.active ? maven ?????
  servlet:
    multipart:
      enabled: true    # ????????
      max-file-size: 10MB    # ?????????????? 10MB?????????????????????
      max-request-size: 100MB    # ????????????????? 100MB?????????????????????????????
  mail:
    host: smtp.qq.com    # ?? QQ ??? SMTP ???????
    port: 587    # SMTP ????????587 ????????????? STARTTLS ??
    username: 2044978721@qq.com    # QQ ???????????
    password: pajdcdkinctsbchd    # QQ ????????????????????????
    protocol: smtp    # ???? SMTP ??????
    properties.mail.smtp.auth: true    # ?? SMTP ???????????????????????
    properties.mail.smtp.starttls.enable: true    # ?? STARTTLS ?????????????
    properties.mail.smtp.starttls.required: true    # ?????? STARTTLS ?????????????????
    properties.mail.smtp.ssl.enable: false    # ??? SSL ???????? STARTTLS?????????
    default-encoding: utf-8    # ???????????? UTF-8????????????????????????
  datasource:
    url: jdbc:mysql://47.117.92.199:3306/shengdonghanyu?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: a13738780767
  #  main:
  #    banner-mode: off    # ?? Spring Boot ????????????????
  jackson:
    time-zone: GMT+8    # ?? Jackson ????????????? GMT+8???????????????????????????
    default-property-inclusion: non_null    # ?? Jackson ??????????? null ?????? JSON ???????
#  jpa:
#    hibernate:
#      ddl-auto: update    # ?? Hibernate ??????????????????????????????????????
#    show-sql: true    # ?? SQL ????????????? Hibernate ??? SQL ????????????
  data:
    redis:
      database: 0
      host: 47.117.92.199
      port: 6379
      timeout: 1000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
          time-between-eviction-runs: 10s    # ?? Redis ????????????? 10 ????????????????????
#    mongodb:
#      uri: mongodb://localhost:27017/springboot_template    # MongoDB ?? URI????????? MongoDB ?????? springboot_template ???
#  elasticsearch:
#    uris: http://localhost:9200    # Elasticsearch ????????????? Elasticsearch ??
#  cache:
#    type: redis
#  task:
#    scheduling:
#      pool:
#        size: 20    # ??????????????? 20????????? 20 ??????????????
#      thread-name-prefix: task-    # ???????????????? task-????????????????
#      shutdown:
#        await-termination: false    # ??????????????????????????????????????????????????
#        await-termination-period: 60s    # ?? await-termination ??? true????????????? 60 ?????????????????????????
#  activemq:
#    broker-url: tcp://localhost:61616    # ActiveMQ ??????? URL????????? ActiveMQ ??
#    user: admin    # ?? ActiveMQ ????????
#    password: admin    # ?? ActiveMQ ???????
#  jms:
#    template:
#      default-destination: test.queue    # ????? JMS ??????? test.queue?????????????????????
#    pub-sub-domain: true    # ????/????????????Topic??????Queue??????????????????????????
#  rabbitmq:
#    host: localhost
#    port: 5672
#  kafka:
#    bootstrap-servers: localhost:9092    # Kafka ???????????????? Kafka ??
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer    # Kafka ?????????????????????????
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer    # Kafka ?????????????????????????
#    consumer:
#      group-id: my-consumer-group    # Kafka ??????????????????????
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer    # Kafka ???????????????????????????
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer    # Kafka ???????????????????????????

#rocketmq:
#  name-server: localhost:9876    # RocketMQ NameServer ???????????? RocketMQ ??
#  producer:
#    group: my-producer-group    # RocketMQ ??????????????????????
#  consumer:
#    group: my-consumer-group    # RocketMQ ??????????????????????
#    enable-orderly: false    # ???????????????????????????????
#    consume-thread-min: 10    # ??????????????? 10?????????????
#    consume-thread-max: 20    # ??????????????? 20?????????????

#jetcache:
#  statIntervalMinutes: 15    # ?? JetCache ?????????? 15 ??????????????????????????????
#  area: springboot_template    # ?? JetCache ???????? springboot_template????????????????????????
#  local:
#    default:
#      type: caffeine    # ?? Caffeine ?????????Caffeine ??????? Java ?????????????????
#      keyConvertor: fastjson2    # ?? Fastjson2 ??????????????????????????????????
#      limit: 1000    # ???????????? 1000 ??????????????
#      valueEncoder: java    # ?? Java ??????????????????????????????
#      valueDecoder: java
#      expireAfterWriteInMillis: 3600000    # ??????????? 1 ???3600000 ??????????????????
#  remote:
#    default:
#      type: redis    # ?? Redis ???????????????????????
#      host: localhost
#      port: 6379
#      poolConfig:
#        maxTotal: 8    # ?? Redis ?????????? 8???????????
#        maxIdle: 8    # ?? Redis ???????????? 8?????????????
#        minIdle: 0    # ?? Redis ???????????? 0????????????????
#      keyConvertor: fastjson2    # ?? Fastjson2 ??????????????????????????????????
#      valueEncoder: java    # ?? Java ??????????????????????????????
#      valueDecoder: java
#      expireAfterWriteInMillis: 86400000    # ??????????? 24 ???86400000 ??????????????????

#j2cache:
#  config-location: classpath:j2cache.properties    # ?? J2Cache ?????????? classpath ???? j2cache.properties ????? J2Cache ?????????

server:
  port: 8088    # HTTPS ???????? 443???????????????????
  ssl:
    key-store-password: fmk5cw9q    # jks-password.txt ??????
    key-store-type: JKS    # JKS ??????????PFX ??????????? PKCS12
    key-store: classpath:shengdonghanyu.com.jks    # ????????????? domain_name.jks
  tomcat:
    uriEncoding: UTF-8    # ???? UTF-8 ???? URL ??????????????????????????????????????
  servlet:
    encoding:
      force: true    # ???????????????????????? UTF-8 ?????
      charset: UTF-8    # ????????????? UTF-8???????????????????
      enabled: true    # ?? Spring Boot ??????????????????? true????????????????????????? ??????????????????
        # Spring Boot ???? HttpEncodingAutoConfiguration ????????????????????????? CharacterEncodingFilter??????????
      # CharacterEncodingFilter ????????Request?????Response???????????????? servlet.encoding.charset ??? UTF-8??

mybatis-plus:
  global-config:
    db-config:
      field-strategy: not_null    # ?? MyBatis-Plus ?????????? not_null????????????????????????? SQL ??????? null ??????
      #      id-type: assign_id    # ??????? assign_id??????? MyBatis-Plus ??????????????????????????
      #      table-prefix: tbl_    # ????????? tbl_?MyBatis-Plus ??? SQL ?????????????????????????
      logic-delete-field: deleted    # ???????? deleted?MyBatis-Plus ???????????????????????????????????????
      logic-not-delete-value: 0    # ???????????? 0?????????
      logic-delete-value: 1    # ??????????? 1???????????
  #    banner: false    # ?? MyBatis-Plus ????????????????
  configuration:
    map-underscore-to-camel-case: true    # ?????????????????????????? user_name?????? Java ??????????? userName?
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    # ?? MyBatis ????????????? SQL ??????????????????? SQL

#logback:
#  dir: logs    # ????????
#  filename:
#    all: springboot-base-frame-all    # ???????
#    info: springboot-base-frame-info    # ?????????
#    warn: springboot-base-frame-warn    # ?????????
#    error: springboot-base-frame-error    # ?????????
#  maxhistory: 10    # ???????????????????????????
#  maxfilesize: 100MB    # ???????????????????????????
#  level: debug    # ??????????debug ????? debug?info?warn?error ???????
#  charset: UTF-8    # ????????????? UTF-8 ????????
#  CONSOLE_LOG_PATTERN: '%d{yyyy-MM-dd HH:mm:ss.SSS} %boldYellow([%thread]) %highlight(%-5level) %boldGreen(%logger{50}) - %msg%n'    # ?????????
#  FILE_LOG_PATTERN: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'    # ????????

#logging:
#  level:
#    org.springframework.jdbc.support.JdbcTransactionManager: DEBUG    # ?? Spring JDBC ??????????? DEBUG???????????????


## ??????
#app:
#  notice:
#    dev-emails: 2044978721@qq.com
#
#---
## ??
#spring:
#  config:
#    activate:
#      on-profile: dev
#
#server:
#  port: 80
#
#---
## ??
#spring:
#  config:
#    activate:
#      on-profile: pro
#
#server:
#  port: 81
#
#---
## ??
#spring:
#  config:
#    activate:
#      on-profile: test
#
#server:
#  port: 82
#
#---